name: "CI for Application"

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
    branches:
      - main

env:
  DOCKER_REGISTRY: davidh83110/flask-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit --no-cache-dir
        pip install semgrep --no-cache-dir
        pip install pipenv --no-cache-dir
        pipenv install --system --deploy --ignore-pipfile
    - name: Run Unittest
      run: |
        pipenv run pytest
    - name: Run Bandit for Python Common Security Check
      run: |
        bandit -r .
    - name: Run Semgreo for SAST(Static Application Security Testing)
      run: |
        semgrep --config r/ci
    - name: Docker buildx Setup
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      run: |
        docker login "${{ env.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Build Image and Push
      run: |
        docker build -t flask-app .
        docker tag flask-app:latest "${{ env.DOCKER_REGISTRY }}":"${{ github.ref_name }}"
        docker push "${{ env.DOCKER_REGISTRY }}":"${{ github.ref_name }}"
    - name: Log out from Docker Hub
      run: docker logout
    - name: Package Helm Chart
      run: helm package deploy/charts -d chart-"${{ github.ref_name }}"
